#! /bin/bash

DEBUG=${DEBUG:-false}
progn="${0##*/}"    # basename
logf="/tmp/$progn.log"  # logfile

# check for tty, otherwise output to log file
[ -t 1 ] || exec > "$logf" 2>&1

usage () {
    cat <<_EOL_

    $progn <URL>

    Chooser to open a browser with a given URL.

_EOL_
    exit
}

# Print Debugging
pd () {
    $DEBUG && echo -ne "[DEBUG] $@\n" 
}

# Argument Handling
case $1 in
    -*) usage ;;
    '') export URL="about:blank"  ;;
    *) export URL="$1"  ;;
esac

# Launchers -- definitions
l_firefox() { firefox --new-window "$URL" ; } ; export -f l_firefox
l_chrome() { google-chrome --new-window "$URL" ; } ; export -f l_chrome

# Define our YAD command.
cmd=( yad
    --window-icon="applications-internet"
    #--geometry=100x160
    #--borders="15"
    --close-on-unfocus
    #--separator=""
    --image="browser"
    --skip-taskbar
    --text="URL = $URL"
    --form 
        --title "Choose Browser:"
        # Launchers invoked from here
        --field="Firefox!:FBTN" "bash -c 'l_firefox'"
        --field="Chrome!:FBTN" "bash -c 'l_chrome'"
        --button="Cancel!gtk-cancel"
    )

pd $(printf "\n---\n%(%Y%m%d-%H%M%S)T\n---" -1)
pd "Executing: ${cmd[@]}"

# Execute YAD command
"${cmd[@]}" ;  _RET=$?

pd "Exited with return value $_RET"

